"""
IDV v1.5 — HuggingFace external validation.

Streams a balanced slice from saberzl/SID_Set (CC-BY-4.0), runs the existing
authenticity adapters (VLM + ELA), computes the same APCER/BPCER/ACER/AUC
metrics as v1, and writes results/idv_run_v1_5.json plus an inline comparison
to v1 synthetic numbers.

Framing: cross-synthetic-generator generalization test.  The v1 corpus was
generated by this project's own pipeline.  SID_Set was produced by a different
pipeline.  A metric drop here means the detector over-fits to our rendering
artefacts; stable metrics mean it reasons about document structure.

Dataset labels (decoded from img_id prefix):
  label=1, img_id starts full_synthetic_  → genuine untampered document
  label=2, img_id starts tampered_        → forged/tampered document
  label=0, UUID img_id                    → ambiguous — skipped

Usage:
  python -m idv.hf_validation                     # 150 streamed, 30 VLM
  python -m idv.hf_validation --n-vlm 40          # 40 VLM calls
  python -m idv.hf_validation --dry-run           # cost estimate, no VLM spend
  python -m idv.hf_validation --vlm-mode api      # use Anthropic key instead
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import numpy as np
from PIL import Image

REPO_ROOT   = Path(__file__).parent.parent
IDV_DATA    = REPO_ROOT / "idv" / "data"
HF_VAL_DIR  = IDV_DATA / "hf_validation"
MANIFEST    = REPO_ROOT / "idv" / "manifest.json"
V1_RESULT   = REPO_ROOT / "results" / "idv_run.json"
V15_RESULT  = REPO_ROOT / "results" / "idv_run_v1_5.json"

HF_DATASET  = "saberzl/SID_Set"
HF_SPLIT    = "validation"
LABEL_GENUINE = 1   # img_id prefix: full_synthetic_
LABEL_FORGED  = 2   # img_id prefix: tampered_

N_STREAM    = 150   # total images to save (75 genuine + 75 forged)
IMG_MAX_PX  = 800   # resize longest edge to this before saving (controls VLM cost)

FIELDS_PLACEHOLDER = ["surname", "given_names", "dob", "doc_number", "expiry", "nationality"]


# ---------------------------------------------------------------------------
# Step 1 — Stream and save images
# ---------------------------------------------------------------------------

def stream_and_save(n_per_class: int = 75, overwrite: bool = False) -> list[dict]:
    """
    Stream balanced genuine/forged examples from HF, save as JPEG, return index.
    Returns list of dicts: {img_id, path, label, hf_label}.
    """
    from datasets import load_dataset

    HF_VAL_DIR.mkdir(parents=True, exist_ok=True)
    index_path = HF_VAL_DIR / "index.json"

    if index_path.exists() and not overwrite:
        print(f"[hf_val] Index already exists ({index_path}). Skipping download. "
              "Pass --overwrite to re-stream.")
        return json.loads(index_path.read_text())["examples"]

    print(f"[hf_val] Streaming from {HF_DATASET} split={HF_SPLIT} "
          f"({n_per_class} genuine + {n_per_class} forged) …")

    ds = load_dataset(HF_DATASET, split=HF_SPLIT, streaming=True)

    genuine_saved, forged_saved = [], []

    for ex in ds:
        label = ex["label"]
        if label == LABEL_GENUINE and len(genuine_saved) < n_per_class:
            bucket = genuine_saved
            tag = "genuine"
        elif label == LABEL_FORGED and len(forged_saved) < n_per_class:
            bucket = forged_saved
            tag = "forged"
        else:
            if len(genuine_saved) >= n_per_class and len(forged_saved) >= n_per_class:
                break
            continue

        img_id  = ex["img_id"]
        pil_img = ex["image"]  # PIL.Image

        # Resize to control VLM token cost
        if pil_img.mode != "RGB":
            pil_img = pil_img.convert("RGB")
        max_side = max(pil_img.size)
        if max_side > IMG_MAX_PX:
            ratio   = IMG_MAX_PX / max_side
            new_w   = int(pil_img.width  * ratio)
            new_h   = int(pil_img.height * ratio)
            pil_img = pil_img.resize((new_w, new_h), Image.LANCZOS)

        fname   = f"{tag}_{img_id[:40].replace('/', '_')}.jpg"
        fpath   = HF_VAL_DIR / fname
        pil_img.save(fpath, "JPEG", quality=90)

        bucket.append({
            "img_id":    img_id,
            "path":      str(fpath),
            "label":     tag,
            "hf_label":  label,
        })

        total = len(genuine_saved) + len(forged_saved)
        if total % 25 == 0:
            print(f"  … {total} / {n_per_class * 2} saved")

    examples = genuine_saved + forged_saved
    index = {
        "dataset":   HF_DATASET,
        "split":     HF_SPLIT,
        "n_genuine": len(genuine_saved),
        "n_forged":  len(forged_saved),
        "license":   "CC-BY-4.0",
        "attribution": (
            "Saber Zl, SID_Set, Hugging Face, 2024. "
            "https://huggingface.co/datasets/saberzl/SID_Set"
        ),
        "label_map": {
            "1 (full_synthetic_*)": "genuine",
            "2 (tampered_*)":       "forged",
        },
        "note": (
            "Cross-synthetic-generator generalization test. "
            "Documents are synthetic (different pipeline from v1 corpus). "
            "Framing: does the VLM authenticity detector transfer across synthetic generators?"
        ),
        "examples": examples,
    }
    index_path.write_text(json.dumps(index, indent=2))
    print(f"[hf_val] Saved {len(genuine_saved)} genuine + {len(forged_saved)} forged → {HF_VAL_DIR}")
    return examples


# ---------------------------------------------------------------------------
# Step 2 — Run ELA baseline on all examples
# ---------------------------------------------------------------------------

def run_ela_all(examples: list[dict]) -> list[dict]:
    sys.path.insert(0, str(REPO_ROOT))
    from idv.adapters.auth_baseline import ELABaselineAdapter

    adapter = ELABaselineAdapter()
    rows = []
    print(f"[hf_val] Running ELA on {len(examples)} documents …")
    for ex in examples:
        t0 = time.time()
        result = adapter.run(ex["path"])
        latency = int((time.time() - t0) * 1000)
        rows.append({
            "img_id":      ex["img_id"],
            "label":       ex["label"],
            "adapter":     "auth_baseline",
            "decision":    result.decision,
            "confidence":  result.confidence,
            "latency_ms":  latency,
            "cost_usd":    result.cost_usd,
        })
    return rows


# ---------------------------------------------------------------------------
# Step 3 — Run VLM on a balanced subset
# ---------------------------------------------------------------------------

def run_vlm_subset(examples: list[dict], n_vlm: int, vlm_mode: str,
                   dry_run: bool = False) -> list[dict]:
    sys.path.insert(0, str(REPO_ROOT))
    from idv.adapters.vlm_doc_auth import VLMDocAuthAdapter

    n_each = n_vlm // 2
    genuine_ex  = [e for e in examples if e["label"] == "genuine"][:n_each]
    forged_ex   = [e for e in examples if e["label"] == "forged"][:n_each]
    subset      = genuine_ex + forged_ex

    est_cost_per_doc = 0.076 * (IMG_MAX_PX / 640) ** 0.8  # rough scaling
    est_total        = est_cost_per_doc * len(subset)
    print(f"[hf_val] VLM subset: {len(genuine_ex)} genuine + {len(forged_ex)} forged "
          f"(~${est_total:.2f} estimated)")

    if dry_run:
        print("[hf_val] --dry-run: skipping VLM calls.")
        return []

    adapter = VLMDocAuthAdapter(vlm_mode=vlm_mode)
    rows = []
    total_cost = 0.0
    for i, ex in enumerate(subset):
        t0 = time.time()
        result = adapter.run(ex["path"])
        latency = int((time.time() - t0) * 1000)
        total_cost += result.cost_usd
        rows.append({
            "img_id":      ex["img_id"],
            "label":       ex["label"],
            "adapter":     "vlm_doc_auth",
            "decision":    result.decision,
            "confidence":  result.confidence,
            "reasoning":   (result.reasoning or "")[:300],
            "latency_ms":  latency,
            "cost_usd":    result.cost_usd,
        })
        print(f"  [{i+1:2d}/{len(subset)}] {ex['label']:8s}  "
              f"decision={'genuine' if result.decision else 'forged':8s}  "
              f"conf={result.confidence:.2f}  cost=${result.cost_usd:.4f}  "
              f"cumulative=${total_cost:.4f}")

    print(f"[hf_val] VLM total spend: ${total_cost:.4f}")
    return rows


# ---------------------------------------------------------------------------
# Step 4 — Compute metrics and assemble result
# ---------------------------------------------------------------------------

def compute_auth_block(rows: list[dict], adapter_id: str, n_genuine_total: int,
                       n_forged_total: int) -> dict:
    sys.path.insert(0, str(REPO_ROOT))
    from eval.metrics import compute_doc_auth_metrics

    decisions   = [r["decision"]   for r in rows]
    labels      = [r["label"]      for r in rows]
    confidences = [r.get("confidence") for r in rows]
    costs       = [r.get("cost_usd", 0.0) for r in rows]
    latencies   = [r.get("latency_ms", 0)  for r in rows]

    m = compute_doc_auth_metrics(decisions, labels, confidences)

    lat_arr  = np.array(latencies) if latencies else np.array([0])
    usd_total = sum(costs)
    n         = len(rows)

    return {
        "adapter_id":          adapter_id,
        "operating_threshold": 0.5,
        "apcer":               m["apcer"],
        "bpcer":               m["bpcer"],
        "acer":                m["acer"],
        "auc":                 m["auc"],
        "by_forgery_type": [{"forgery_type": "tampered", "apcer": m["apcer"],
                              "n": m["n_forged"]}],
        "roc":                 m["roc"],
        "cost": {
            "calls":       n,
            "tokens_in":   0,
            "tokens_out":  0,
            "usd_total":   usd_total,
            "usd_per_doc": usd_total / n if n else 0.0,
        },
        "latency_ms": {
            "p50": int(np.percentile(lat_arr, 50)),
            "p95": int(np.percentile(lat_arr, 95)),
        },
    }


def build_comparison(v1_path: Path, v15_adapters: list[dict]) -> dict:
    """Side-by-side v1 vs v1.5 for each adapter."""
    if not v1_path.exists():
        return {"note": "v1 result not found — cannot compare."}

    v1 = json.loads(v1_path.read_text())
    v1_adapters = {a["adapter_id"]: a for a in v1["authenticity"]["adapters"]}
    v15_adapters_map = {a["adapter_id"]: a for a in v15_adapters}

    comparison = {}
    for aid in set(list(v1_adapters.keys()) + list(v15_adapters_map.keys())):
        v1a  = v1_adapters.get(aid, {})
        v15a = v15_adapters_map.get(aid, {})
        comparison[aid] = {
            "v1_synthetic": {
                "apcer": v1a.get("apcer"),
                "bpcer": v1a.get("bpcer"),
                "acer":  v1a.get("acer"),
                "auc":   v1a.get("auc"),
                "n":     (v1["authenticity"]["n_genuine"] + v1["authenticity"]["n_forged"])
                         if v1a else None,
            },
            "v1_5_hf": {
                "apcer": v15a.get("apcer"),
                "bpcer": v15a.get("bpcer"),
                "acer":  v15a.get("acer"),
                "auc":   v15a.get("auc"),
                "n":     (v15a["cost"]["calls"]) if v15a.get("cost") else None,
            },
        }
        # Delta (v1.5 − v1); positive = worse
        if v1a and v15a:
            comparison[aid]["acer_delta"]  = round(
                (v15a.get("acer", 0) or 0) - (v1a.get("acer", 0) or 0), 4)
            comparison[aid]["auc_delta"]   = round(
                (v15a.get("auc", 0)  or 0) - (v1a.get("auc",  0) or 0), 4)

    return comparison


# ---------------------------------------------------------------------------
# Step 5 — Update manifest
# ---------------------------------------------------------------------------

def update_manifest() -> None:
    m = json.loads(MANIFEST.read_text())
    m["tasks"]["hf_authenticity_validation"] = {
        "dataset":     "SID_Set (saberzl/SID_Set)",
        "description": (
            "HuggingFace validation slice for cross-synthetic-generator "
            "generalization. 75 genuine (label=1, full_synthetic_*) + "
            "75 forged (label=2, tampered_*) from the validation split."
        ),
        "source_url":  "https://huggingface.co/datasets/saberzl/SID_Set",
        "license":     "CC-BY-4.0",
        "attribution": (
            "Saber Zl, SID_Set, Hugging Face, 2024."
        ),
        "local_path":  "idv/data/hf_validation/",
        "subset":      "75_genuine_75_forged_validation_split",
        "subset_seed": "streaming_order",
        "n_genuine":   75,
        "n_forged":    75,
        "note":        (
            "Synthetic (different pipeline from v1). "
            "Framing: cross-generator generalization, not real-world validation."
        ),
        "status": "ready",
    }
    MANIFEST.write_text(json.dumps(m, indent=2))
    print(f"[hf_val] Updated {MANIFEST}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="IDV v1.5 HuggingFace validation")
    parser.add_argument("--vlm-mode", choices=["cli", "api", "local"], default="cli")
    parser.add_argument("--n-vlm",    type=int, default=30,
                        help="Number of docs to run VLM on (split 50/50). Default 30.")
    parser.add_argument("--overwrite", action="store_true",
                        help="Re-stream images even if already downloaded.")
    parser.add_argument("--dry-run",  action="store_true",
                        help="Skip VLM calls; show cost estimate only.")
    args = parser.parse_args()

    print("\n=== IDV v1.5 — HuggingFace External Validation ===")
    print(f"Dataset  : {HF_DATASET} (CC-BY-4.0, synthetic)")
    print(f"Framing  : cross-synthetic-generator generalization")
    print(f"VLM mode : {args.vlm_mode}  n_vlm={args.n_vlm}")
    print(f"Task     : authenticity only (SID_Set has no field-level GT)")
    print()

    # 1. Stream images
    n_per_class = N_STREAM // 2
    examples = stream_and_save(n_per_class=n_per_class, overwrite=args.overwrite)

    # 2. ELA on all
    ela_rows = run_ela_all(examples)

    # 3. VLM on subset
    vlm_rows = run_vlm_subset(examples, n_vlm=args.n_vlm,
                              vlm_mode=args.vlm_mode, dry_run=args.dry_run)

    if args.dry_run:
        print("\n[hf_val] Dry run complete. Re-run without --dry-run to spend VLM credits.")
        return

    # 4. Metrics
    n_genuine = sum(1 for e in examples if e["label"] == "genuine")
    n_forged  = sum(1 for e in examples if e["label"] == "forged")

    ela_block = compute_auth_block(ela_rows, "auth_baseline", n_genuine, n_forged)
    vlm_block = compute_auth_block(vlm_rows, "vlm_doc_auth",  n_genuine, n_forged)

    total_cost = sum(r["cost_usd"] for r in vlm_rows)

    # 5. Comparison
    comparison = build_comparison(V1_RESULT, [ela_block, vlm_block])

    # 6. Assemble result (schema_version idv-1.5 — authenticity-only shape)
    run_id = hashlib.sha1(
        f"{HF_DATASET}{datetime.now(timezone.utc).isoformat()}".encode()
    ).hexdigest()[:8]

    result = {
        "schema_version": "idv-1.5",
        "run": {
            "id":              run_id,
            "timestamp":       datetime.now(timezone.utc).isoformat(),
            "vlm_mode":        args.vlm_mode,
            "total_cost_usd":  total_cost,
            "note":            (
                "Authenticity-only validation on HuggingFace SID_Set. "
                "Extraction and face-match not evaluated — SID_Set has no "
                "field-level ground truth or face pairs."
            ),
        },
        "source": {
            "dataset":     HF_DATASET,
            "split":       HF_SPLIT,
            "license":     "CC-BY-4.0",
            "attribution": (
                "Saber Zl, SID_Set, Hugging Face, 2024. "
                "https://huggingface.co/datasets/saberzl/SID_Set"
            ),
            "is_synthetic": True,
            "framing": (
                "Cross-synthetic-generator generalization: documents generated "
                "by a different pipeline than the v1 synthetic corpus. "
                "A metric drop signals over-fitting to v1 rendering artefacts; "
                "stable metrics signal structural reasoning."
            ),
        },
        "authenticity": {
            "dataset":   f"{HF_DATASET} ({HF_SPLIT} split)",
            "n_genuine": n_genuine,
            "n_forged":  n_forged,
            "n_ela":     len(ela_rows),
            "n_vlm":     len(vlm_rows),
            "adapters":  [vlm_block, ela_block],
        },
        "generalization_comparison": comparison,
    }

    V15_RESULT.parent.mkdir(parents=True, exist_ok=True)
    V15_RESULT.write_text(json.dumps(result, indent=2))
    print(f"\n[hf_val] Result written → {V15_RESULT}")
    print(f"[hf_val] Total VLM spend: ${total_cost:.4f}")

    # 7. Print comparison summary
    print("\n=== Generalization check: v1 synthetic → v1.5 HF ===")
    for aid, c in comparison.items():
        v1a, v15a = c.get("v1_synthetic", {}), c.get("v1_5_hf", {})
        print(f"\n  {aid}")
        print(f"    v1  (n={v1a.get('n','?'):3})  APCER={v1a.get('apcer','?')}  "
              f"ACER={v1a.get('acer','?')}  AUC={v1a.get('auc','?')}")
        print(f"    v1.5(n={v15a.get('n','?'):3})  APCER={v15a.get('apcer','?')}  "
              f"ACER={v15a.get('acer','?')}  AUC={v15a.get('auc','?')}")
        if "acer_delta" in c:
            delta_sign = "▲" if c["acer_delta"] > 0.01 else ("▼" if c["acer_delta"] < -0.01 else "≈")
            print(f"    ΔACER={c['acer_delta']:+.4f}  ΔAUC={c['auc_delta']:+.4f}  {delta_sign}")

    # 8. Update manifest
    update_manifest()
    print("\n[hf_val] Done.")


if __name__ == "__main__":
    main()
