"""
IDV v1.5 — SIDTD external validation.

Downloads a stratified sample of real ID-document images from the SIDTD
templates subset (http://datasets.cvc.uab.es/SIDTD/templates.zip) using
HTTP range requests — no need to pull the full 1.27 GB archive.

Forgery type labels map to SIDTD forgery codes:
  fake_0..fake_9  — ten distinct forgery methods generated by the SIDTD
                    DataGenerator (photo substitution, field overwrite, etc.)

Runs vlm_doc_auth on each image, computes APCER/BPCER/ACER/AUC broken out
by forgery type, and writes results/idv_run_v1_5.json.

Usage:
  python -m idv.sidtd_validation               # 20 genuine + 20 forged
  python -m idv.sidtd_validation --n 15        # 15 + 15
  python -m idv.sidtd_validation --dry-run     # download only, no VLM spend
  python -m idv.sidtd_validation --vlm-mode api

Attribution:
  Berenguel-Baeta, B., Mas-Sanso, J., Lladós, J. (2022).
  SIDTD: A Synthetic Identity Document Tampering Detection dataset.
  CC BY-SA 2.5. https://github.com/BCV-Uniandes/SIDTD
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
import time
import zlib
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

REPO_ROOT   = Path(__file__).parent.parent
IDV_DATA    = REPO_ROOT / "idv" / "data"
SIDTD_DIR   = IDV_DATA / "sidtd" / "templates_val"
V1_RESULT   = REPO_ROOT / "results" / "idv_run.json"
V15_RESULT  = REPO_ROOT / "results" / "idv_run_v1_5.json"

TEMPLATES_URL = "http://datasets.cvc.uab.es/SIDTD/templates.zip"

# Forgery type names (SIDTD numbering 0-9)
FORGERY_NAMES = {
    "fake_0": "background_noise",
    "fake_1": "photo_substitution",
    "fake_2": "field_overwrite",
    "fake_3": "color_shift",
    "fake_4": "font_change",
    "fake_5": "border_removal",
    "fake_6": "blurring",
    "fake_7": "jpeg_artefact",
    "fake_8": "rotation",
    "fake_9": "cropping",
}

# ─── Central directory reader ──────────────────────────────────────────────────

def _read_central_directory(url: str) -> list[dict]:
    """
    Fetch only the zip central directory via two HTTP range requests.
    Returns a list of dicts with keys: fname, comp_size, uncomp_size,
    local_hdr_offset, comp_method.
    """
    import urllib.request

    def range_get(start: int, end: int) -> bytes:
        req = urllib.request.Request(url, headers={"Range": f"bytes={start}-{end}"})
        with urllib.request.urlopen(req, timeout=60) as r:
            return r.read()

    # 1. Get last 22 bytes to find EOCD
    head_resp = urllib.request.urlopen(
        urllib.request.Request(url, method="HEAD"), timeout=30
    )
    total = int(head_resp.headers["Content-Length"])

    # EOCD is in last 65KB
    tail = range_get(max(0, total - 65536), total - 1)
    eocd_off = tail.rfind(b"PK\x05\x06")
    if eocd_off < 0:
        raise RuntimeError("EOCD not found — zip may be corrupt")
    eocd = tail[eocd_off:]
    _, _, _, _, cd_size, cd_offset, _ = struct.unpack("<HHHHIIH", eocd[4:22])

    # 2. Fetch central directory
    cd = range_get(cd_offset, cd_offset + cd_size - 1)

    entries = []
    pos = 0
    while pos < len(cd) - 4:
        if cd[pos : pos + 4] != b"PK\x01\x02":
            break
        (_, _, _, comp_method, _, _, _, comp_size, uncomp_size,
         fname_len, extra_len, comment_len, _, _, _, local_hdr_offset) = struct.unpack(
            "<HHHHHHI II HHHH HII", cd[pos + 4 : pos + 46]
        )
        fname = cd[pos + 46 : pos + 46 + fname_len].decode("utf-8", errors="replace")
        entries.append(
            dict(
                fname=fname,
                comp_size=comp_size,
                uncomp_size=uncomp_size,
                local_hdr_offset=local_hdr_offset,
                comp_method=comp_method,
            )
        )
        pos += 46 + fname_len + extra_len + comment_len
    return entries


def _download_zip_entry(url: str, entry: dict) -> bytes:
    """
    Download and decompress a single entry from a remote zip using range requests.
    Handles deflate (method=8) and stored (method=0).
    """
    import urllib.request

    def range_get(start: int, end: int) -> bytes:
        req = urllib.request.Request(url, headers={"Range": f"bytes={start}-{end}"})
        with urllib.request.urlopen(req, timeout=120) as r:
            return r.read()

    off = entry["local_hdr_offset"]
    # Local file header: 30 fixed + fname_len + extra_len (may differ from cd extra_len)
    lhdr = range_get(off, off + 29)
    if lhdr[:4] != b"PK\x03\x04":
        raise RuntimeError(f"Local header signature missing for {entry['fname']}")
    fname_len_local = struct.unpack("<H", lhdr[26:28])[0]
    extra_len_local = struct.unpack("<H", lhdr[28:30])[0]
    data_start = off + 30 + fname_len_local + extra_len_local

    compressed = range_get(data_start, data_start + entry["comp_size"] - 1)
    if entry["comp_method"] == 8:
        return zlib.decompress(compressed, wbits=-15)
    elif entry["comp_method"] == 0:
        return compressed
    else:
        raise RuntimeError(f"Unsupported compression method {entry['comp_method']}")


# ─── Dataset preparation ───────────────────────────────────────────────────────

def build_sample(n_per_class: int = 20) -> list[dict]:
    """
    Download a stratified SIDTD sample to SIDTD_DIR.
    Returns list of dicts with keys: path, label, country, doc_type, forgery_type.
    """
    SIDTD_DIR.mkdir(parents=True, exist_ok=True)
    cache_path = SIDTD_DIR / "manifest.json"

    # Reload from disk if already done
    if cache_path.exists():
        manifest = json.loads(cache_path.read_text())
        reals = [e for e in manifest if e["label"] == "genuine"]
        fakes = [e for e in manifest if e["label"] == "forged"]
        if len(reals) >= n_per_class and len(fakes) >= n_per_class:
            print(f"  Loaded {len(reals)} genuine + {len(fakes)} forged from cache.")
            return manifest

    print("  Reading SIDTD central directory …")
    entries = _read_central_directory(TEMPLATES_URL)
    imgs = [e for e in entries if e["fname"].endswith((".jpg", ".png", ".JPG", ".PNG"))]
    reals_all = [e for e in imgs if "/reals/" in e["fname"]]
    fakes_all  = [e for e in imgs if "/fakes/" in e["fname"]]

    def country(fname: str) -> str:
        return fname.split("/")[-1].split("_")[0]  # alb, aze, esp, …

    def forgery_type(fname: str) -> str:
        base = fname.split("/")[-1].replace(".jpg", "").replace(".png", "")
        parts = base.split("_fake_")
        return "fake_" + parts[1].split("_")[0] if len(parts) > 1 else "genuine"

    def doc_type(fname: str) -> str:
        base = fname.split("/")[-1]
        parts = base.split("_")
        return parts[1] if len(parts) > 1 else "unknown"

    # Stratified: pick n_per_class genuine docs across countries
    countries = sorted({country(e["fname"]) for e in reals_all})
    per_country = max(1, n_per_class // len(countries))
    remainder   = n_per_class - per_country * len(countries)

    selected_reals = []
    for i, c in enumerate(countries):
        pool = [e for e in reals_all if country(e["fname"]) == c]
        take = per_country + (1 if i < remainder else 0)
        selected_reals.extend(pool[:take])
    selected_reals = selected_reals[:n_per_class]

    # Forged: one per forgery type, balanced across countries
    ftypes = sorted(FORGERY_NAMES.keys())
    per_ftype = max(1, n_per_class // len(ftypes))
    selected_fakes = []
    for ft in ftypes:
        pool = [e for e in fakes_all if forgery_type(e["fname"]) == ft]
        selected_fakes.extend(pool[:per_ftype])
    # Top up if needed
    if len(selected_fakes) < n_per_class:
        extras = [e for e in fakes_all if e not in selected_fakes]
        selected_fakes.extend(extras[: n_per_class - len(selected_fakes)])
    selected_fakes = selected_fakes[:n_per_class]

    manifest = []
    total = selected_reals + selected_fakes
    for i, entry in enumerate(total):
        fname = entry["fname"]
        label = "genuine" if "/reals/" in fname else "forged"
        safe_name = fname.replace("/", "_")
        dest = SIDTD_DIR / safe_name
        if not dest.exists():
            print(f"  [{i+1}/{len(total)}] Downloading {fname.split('/')[-1]} ({entry['comp_size']//1024} KB) …")
            data = _download_zip_entry(TEMPLATES_URL, entry)
            dest.write_bytes(data)
        manifest.append(
            dict(
                path=str(dest),
                label=label,
                country=country(fname),
                doc_type=doc_type(fname),
                forgery_type=forgery_type(fname) if label == "forged" else None,
            )
        )
    cache_path.write_text(json.dumps(manifest, indent=2))
    print(f"  Downloaded {len(selected_reals)} genuine + {len(selected_fakes)} forged.")
    return manifest


# ─── VLM eval ─────────────────────────────────────────────────────────────────

def run_vlm_eval(
    examples: list[dict],
    vlm_mode: str = "cli",
    cache_path: Optional[Path] = None,
) -> list[dict]:
    """Run vlm_doc_auth on all examples, caching per-image results."""
    from idv.adapters.vlm_doc_auth import VLMDocAuthAdapter

    adapter = VLMDocAuthAdapter(vlm_mode=vlm_mode, skip_permissions=True)
    cache: dict[str, dict] = {}
    if cache_path and cache_path.exists():
        cache = json.loads(cache_path.read_text())

    results = []
    n = len(examples)
    for i, ex in enumerate(examples):
        img_hash = hashlib.md5(Path(ex["path"]).read_bytes()).hexdigest()[:12]
        if img_hash in cache:
            r = cache[img_hash]
            print(f"  [{i+1}/{n}] {Path(ex['path']).name} — cached ({r['decision']}, conf={r['confidence']:.2f})")
        else:
            print(f"  [{i+1}/{n}] {Path(ex['path']).name} … ", end="", flush=True)
            t0 = time.time()
            auth = adapter.run(ex["path"])
            elapsed = time.time() - t0
            r = dict(
                decision=auth.decision,
                confidence=auth.confidence if auth.confidence is not None else 0.5,
                cost_usd=auth.cost_usd,
                latency_ms=auth.latency_ms or int(elapsed * 1000),
            )
            cache[img_hash] = r
            if cache_path:
                cache_path.write_text(json.dumps(cache, indent=2))
            print(f"{'GENUINE' if r['decision'] else 'FORGED'}  conf={r['confidence']:.2f}  ${r['cost_usd']:.4f}")

        results.append({**ex, **r})
    return results


# ─── Metrics ──────────────────────────────────────────────────────────────────

def compute_metrics(rows: list[dict]) -> dict:
    import sys
    sys.path.insert(0, str(REPO_ROOT))
    from eval.metrics import compute_doc_auth_metrics

    decisions   = [r["decision"] for r in rows]
    labels      = [r["label"] for r in rows]
    confidences = [r["confidence"] for r in rows]

    metrics = compute_doc_auth_metrics(decisions, labels, confidences)

    # Per forgery-type breakdown
    by_ftype = defaultdict(list)
    for r in rows:
        if r["label"] == "forged":
            by_ftype[r["forgery_type"]].append(r)

    by_forgery = []
    for ft, rows_ft in sorted(by_ftype.items()):
        n = len(rows_ft)
        apcer_ft = sum(1 for r in rows_ft if r["decision"] is True) / n if n > 0 else 0.0
        by_forgery.append(
            dict(
                forgery_type=ft,
                forgery_name=FORGERY_NAMES.get(ft, ft),
                apcer=round(apcer_ft, 4),
                n=n,
            )
        )

    return {**metrics, "by_forgery_type": by_forgery}


def build_comparison(v15_metrics: dict) -> dict:
    """Inline comparison to v1 synthetic numbers for the Results page."""
    if not V1_RESULT.exists():
        return {}
    v1 = json.loads(V1_RESULT.read_text())
    v1_adapters = {a["adapter_id"]: a for a in v1.get("authenticity", {}).get("adapters", [])}
    v1_vlm = v1_adapters.get("vlm_doc_auth", {})
    return {
        "vlm_doc_auth": {
            "v1_synthetic": {
                "auc":   v1_vlm.get("auc"),
                "acer":  v1_vlm.get("acer"),
                "apcer": v1_vlm.get("apcer"),
                "bpcer": v1_vlm.get("bpcer"),
                "n":     v1.get("authenticity", {}).get("n_genuine", 0)
                         + v1.get("authenticity", {}).get("n_forged", 0),
            },
            "v1_5_sidtd": {
                "auc":   v15_metrics.get("auc"),
                "acer":  v15_metrics.get("acer"),
                "apcer": v15_metrics.get("apcer"),
                "bpcer": v15_metrics.get("bpcer"),
                "n":     None,
            },
            "auc_delta":  round(
                (v15_metrics.get("auc") or 0) - (v1_vlm.get("auc") or 0), 4
            ),
            "acer_delta": round(
                (v15_metrics.get("acer") or 0) - (v1_vlm.get("acer") or 0), 4
            ),
        }
    }


# ─── Output writer ─────────────────────────────────────────────────────────────

def write_results(rows: list[dict], metrics: dict) -> None:
    total_cost  = sum(r.get("cost_usd", 0.0) for r in rows)
    n_genuine   = sum(1 for r in rows if r["label"] == "genuine")
    n_forged    = sum(1 for r in rows if r["label"] == "forged")

    comparison = build_comparison(metrics)

    out = {
        "schema_version": "idv-1.5",
        "run": {
            "id":            datetime.now(timezone.utc).strftime("sidtd-val-%Y%m%dT%H%M%SZ"),
            "timestamp":     datetime.now(timezone.utc).isoformat(),
            "vlm_mode":      rows[0].get("vlm_mode", "cli") if rows else "cli",
            "total_cost_usd": round(total_cost, 6),
            "note": "External validation on real ID-document forgeries from SIDTD templates.",
        },
        "source": {
            "dataset":      "SIDTD templates",
            "url":          TEMPLATES_URL,
            "license":      "CC BY-SA 2.5",
            "attribution":  (
                "Berenguel-Baeta, B., Mas-Sanso, J., Lladós, J. (2022). "
                "SIDTD: A Synthetic Identity Document Tampering Detection dataset. "
                "https://github.com/BCV-Uniandes/SIDTD"
            ),
            "is_synthetic": False,
            "framing": (
                "Real-world ID document forgeries (scanned templates with "
                "programmatic tampering). Cross-domain test vs v1 synthetic corpus."
            ),
        },
        "authenticity": {
            "dataset":  "SIDTD templates (genuine vs forged)",
            "n_genuine": n_genuine,
            "n_forged":  n_forged,
            "n_countries": len({r["country"] for r in rows}),
            "n_forgery_types": len({r["forgery_type"] for r in rows if r["label"] == "forged"}),
            "adapters": [
                {
                    "adapter_id":          "vlm_doc_auth",
                    "operating_threshold": 0.5,
                    "apcer":  round(metrics.get("apcer", 0), 4),
                    "bpcer":  round(metrics.get("bpcer", 0), 4),
                    "acer":   round(metrics.get("acer", 0), 4),
                    "auc":    round(metrics.get("auc", 0), 4),
                    "by_forgery_type": metrics.get("by_forgery_type", []),
                    "roc":    metrics.get("roc", []),
                }
            ],
        },
        "generalization_comparison": comparison,
    }

    V15_RESULT.parent.mkdir(parents=True, exist_ok=True)
    V15_RESULT.write_text(json.dumps(out, indent=2))
    print(f"\n  Written → {V15_RESULT}")
    print(f"  VLM  AUC={metrics.get('auc', 0):.3f}  ACER={metrics.get('acer', 0):.3f}  "
          f"APCER={metrics.get('apcer', 0):.3f}  BPCER={metrics.get('bpcer', 0):.3f}")
    print(f"  Total spend: ${total_cost:.4f}")


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(description="IDV v1.5 SIDTD validation")
    ap.add_argument("--n",         type=int, default=20, help="docs per class (default 20)")
    ap.add_argument("--vlm-mode",  default="cli",        help="cli / api / local")
    ap.add_argument("--dry-run",   action="store_true",  help="download only, skip VLM")
    args = ap.parse_args()

    print("\n=== IDV v1.5 — SIDTD validation ===\n")

    print(f"Step 1: Download {args.n} genuine + {args.n} forged from SIDTD")
    examples = build_sample(n_per_class=args.n)

    if args.dry_run:
        print("\nDry-run: skipping VLM. Images downloaded to:", SIDTD_DIR)
        return

    cache_path = SIDTD_DIR / "vlm_cache.json"
    print(f"\nStep 2: Run vlm_doc_auth ({args.vlm_mode}) on {len(examples)} docs")
    results = run_vlm_eval(examples, vlm_mode=args.vlm_mode, cache_path=cache_path)

    for r in results:
        r["vlm_mode"] = args.vlm_mode

    print("\nStep 3: Compute metrics")
    metrics = compute_metrics(results)

    print("\nStep 4: Write idv_run_v1_5.json")
    write_results(results, metrics)


if __name__ == "__main__":
    main()
